In [1]:
#Py program to add two numbers.
a=5
b=10
c=a+b

In [2]:
c

15

In [3]:
#Maximum of two numbers
a=5
b= 15

In [7]:
max(a,b)

7

In [12]:
#Py program for factorial of a number
def fract(n):
    if n < 0:
        return 0
    elif n == 0 or n == 1:
        return 1
    else:
        fact = 1
        while( n>1):
            fact *=n
            n -=1
        return fact
n = 10
print(fract(n))

3628800


In [4]:
#Simple interest
P = 29000  #P=Principal/Amount
R = 5     #R= rate of interest
T = 2     #T=Time
SI=(P*R*T)/100
print("Simple Interest is:",SI)

Simple Interest is: 2900.0


In [19]:
#Compound Interest
 
P = 5000  #define principal
r = 0.05    #interest rate
n = 1   #compounding periods per year
t = 10   # total years

#calculate final amount
CI=P*(pow((1+r/n), n*t))
print("Compund Interest is:",CI)


Compund Interest is: 288325.1953125


In [10]:
#Python program to compute compound interest
P = float(input("Enter the principal amount : "))
T = float(input("Enter the number of years : "))
R = float(input("Enter the rate of interest : "))
#compute compound interest
ci =  P * (pow((1 + R / 100), T))
print("Compound interest:",ci)

Enter the principal amount : 5000
Enter the number of years : 10
Enter the rate of interest : .05
Compound interest: 5025.056325065662


In [21]:
#Armstrong Number
num = int(input("Enter any number : "))
sum = 0
n1= len(str(num))
temp = num
#Define a function
while temp > 0:
    digit = temp % 10
    sum += digit ** n1
    temp = temp//10
 
if sum==num:
    print('It is an Armstrong number')
else:
    print('It is not an Armstrong number')

Enter any number : 1634
It is an Armstrong number


In [23]:
#Area of a circle
pi=3.14
R=10
Area= pi*R*R
print("Area of the circle is:",Area)

Area of the circle is: 314.0


In [25]:
#Prime numbers
lower = int(input("Enter lower number : "))
upper = int(input("Enter upper number : "))

print("Prime numbers between", lower, "and", upper, "are:")

for num in range(lower, upper + 1):
   # all prime numbers are greater than 1
   if num > 1:
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           print(num)

Enter lower number : 100
Enter upper number : 200
Prime numbers between 100 and 200 are:
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199


In [26]:
#Check prime numbers
num= 20
if(num%2 == 0):
    print("Number is not a prime Number")
else:
    print("It is a prime number")

Number is not a prime Number


In [28]:
#Fibonacci Number
def Fibonacci_Series(n):   
    # using if-else conditional statement  
    if n < 0:  
        print("Incorrect input")  
    # First Fibonacci number is 0  
    elif n == 0:   
        return (0)   
    # Second Fibonacci number is 1   
    elif n == 1:  
        return (1)  
    else:  
        return (Fibonacci_Series(n - 1) + Fibonacci_Series(n - 2))   
# printing the 12th element of the Fibonacci Series  
print("12th Element of the Fibonacci Series:", Fibonacci_Series(12))  

12th Element of the Fibonacci Series: 144


In [33]:
#Check fibonacci number
def is_fibonacci_number(num):
    a, b = 0, 1
    while a < num:
        a, b = b, a + b

    return a == num

# Example: Check if 21 is a Fibonacci number
number_to_check = 21
if is_fibonacci_number(number_to_check):
    print(f"{number_to_check} is a Fibonacci number.")
else:
    print(f"{number_to_check} is not a Fibonacci number.")


21 is a Fibonacci number.


In [34]:
def findPosition(k, n):
    f1 = 0
    f2 = 1
    i =2; 
    while i!=0:
        f3 = f1 + f2;
        f1 = f2;
        f2 = f3;
 
        if f2%k == 0:
            return n*i
 
        i+=1
         
    return
 
 
# Multiple no.
n = 5;
# Number of whose multiple we are finding
k = 4;
 
print("Position of n\'th multiple of k in"
                "Fibonacci Series is", findPosition(k,n));

Position of n'th multiple of k inFibonacci Series is 30


In [39]:
#Find ASCII value
K = input("Please enter a character: ")    
        
print ("The ASCII value of '" + K + "' is ", ord(K))  

Please enter a character: A
The ASCII value of 'A' is  65


In [40]:
#Sum square of 1st n natural number
def square_sum(n):
    sm = 0
    for i in range(1, n+1):
        sm = sm + (i * i)
 
    return sm
n =int(input("Enter the Number:"))
print(square_sum(n))

Enter the Number:5
55


In [41]:
#Cube of 1st n natural number
def cube_sum(n):
    sm = 0
    for i in range(1, n+1):
        sm = sm + (i * i * i)
 
    return sm
n =int(input("Enter the Number:"))
print(cube_sum(n))

Enter the Number:3
36


In [ ]:
Array Programs

In [47]:
#sum of array
arr = [10, 8, 90, 56, 34, 80, 8]
Sum = 0

for i in range(len(arr)):
   Sum = Sum + arr[i]
print (Sum)

286


In [49]:
#Find the largest element in an array
arr = [25, 41, 77, 99, 56];     
length = len(arr)  
#Initialize max with first element of array.    
max = arr[0];    
        
for i in range(0, length):
    if(arr[i] > max):    
       max = arr[i];    
           
print("Largest element present in given array: " + str(max));

Largest element present in given array: 99


In [51]:
#Array rotation
def rotate_elements(arr, max, no_of_elements):
   temp = []
   i = 0
   while (i < no_of_elements):
      temp.append(arr[i])
      i += 1

   i = 0
   while (no_of_elements < max):
      arr[i] = arr[no_of_elements]
      i = i + 1
      no_of_elements = no_of_elements + 1

   arr[:] = arr[: i] + temp
   return arr
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("The array before rotation is: ", end =' ')
print(arr)
print("The array after rotation is: ", end=' ')
max_size = len(arr)

print(rotate_elements(arr, max_size, 2))

The array before rotation is:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
The array after rotation is:  [3, 4, 5, 6, 7, 8, 9, 10, 1, 2]


In [53]:
#Reversed an array
arr = [10, 20, 30, 40, 50]
print("Before reversal Array is :",arr)
 
arr.reverse() #reversing using reverse()
print("After reversing Array:",arr)

Before reversal Array is : [10, 20, 30, 40, 50]
After reversing Array: [50, 40, 30, 20, 10]


In [57]:
#Split the array and add the first part to the end

def splitArr(arr, n, k):
    for i in range(0, k):
        x = arr[0]
        for j in range(0, n-1):
            arr[j] = arr[j + 1]
 
        arr[n-1] = x
 
 
# main
arr = [12, 10,15, 26, 52, 36]
n = len(arr)
position = 2
 
splitArr(arr, n, position)
 
for i in range(0, n):
    print(arr[i], end=' ')

15 26 52 36 12 10 

In [58]:
#reminder of array multiplication
def findremainder(arr, len, n):
    product = 1
    for i in range(len):
        product = product * arr[i]
    return product % n
 
 
arr = [100, 10, 5, 25, 35, 14]
len = len(arr)
n = 11
print(findremainder(arr, len, n))

9


In [59]:
#check if given array is Monotonic
def isMonotonic(A):
    x, y = [], []
    x.extend(A)
    y.extend(A)
    x.sort()
    y.sort(reverse=True)
    if(x == A or y == A):
        return True
    return False
 
A = [6, 5, 4, 4]
print(isMonotonic(A))


True


In [60]:
#Interchange first and last elements in a list
def swapList(list):
       
    first = list.pop(0)   
    last = list.pop(-1) 
    list.insert(0, last)  
    list.append(first)         
    return list

li = [1, 9, 2, 10, 19, 30]
print(li)
print("Swapped list: ",swapList(li))

[1, 9, 2, 10, 19, 30]
Swapped list:  [30, 9, 2, 10, 19, 1]


In [62]:
#Swap a list
fruits = ["oranges", "grapes", "bananas","Mango"]

print("List of fruits before swap:")
print(fruits)

#swap elements at index 0 and 2
fruits[0], fruits[2] = fruits[2], fruits[0]

print("\nList of fruits after swap:")
print(fruits)

List of fruits before swap:
['oranges', 'grapes', 'bananas', 'Mango']

List of fruits after swap:
['bananas', 'grapes', 'oranges', 'Mango']


In [1]:
#Length of a list
my_list = [1,2,3,4,6,7,8]

In [2]:
len(my_list)

7

In [3]:
#check if the element in a list or not

lst=[ 1, 6, 3, 5, 3, 4 ] 
#checking if element is present or not
# in the given list or not
i=10
# if element present then return
# exist otherwise not exist
if i in lst: 
    print("exist") 
else: 
    print("not exist")


not exist


In [4]:
#Clear the list

A = [62, 30, 23, 10]
print('GEEK before clear:', A)
 
# Clearing list
A.clear()
print('A after clear:', A)


GEEK before clear: [62, 30, 23, 10]
A after clear: []


In [6]:
#Reversed a list
My_numbers = [3, 31, 5, 57]
My_numbers.reverse()
print('Reversed List:', My_numbers)

Reversed List: [57, 5, 31, 3]


In [7]:
#sum of a element in list
numbers = [1, 2, 3, 4, 5]
print(sum(numbers))

15


In [8]:
#Multipy all element in list
import numpy
list1 = [10, 2, 3]
result1 = numpy.prod(list1)
print(result1)

60


In [9]:
#Find smallest element in  a list
list1 = [10, 20, 4, 40, 2]
 
# sorting the list
list1.sort()
 
# printing the first element
print("Smallest element is:", list1[0])

Smallest element is: 2


In [10]:
#find largest number in a list
list1 = [10, 20, 4, 40, 2]
 
# sorting the list
list1.sort()
 
# printing the first element
print("Largest_element is:", list1[-1])


Largest_element is: 40


In [11]:
#Find 2nd largest value
list1 = [10, 20, 4, 40, 2]
 
# sorting the list
list1.sort()
 
# printing the first element
print("Largest_element is:", list1[-2])

Largest_element is: 20


In [12]:
#Python program to find N largest
my_list = [1000, 298, 300, 100, 200, -45, 900]
n = 3
 
my_list.sort()
print(my_list[-n:])

[300, 900, 1000]


In [13]:
#Even numbers from the list
My_list = [3,6,19,11,20,13]
# iterating each number in list
for num in My_list:
 
    # checking condition
    if num % 2 == 0:
        print(num, end=" ")

6 20 

In [16]:
#Python program to print odd numbers in a List
My_list = [3,6,19,11,20,13]
# iterating each number in list
for num in My_list:
 
    # checking condition
    if num % 2 != 0:
        print(num, end=" ")

3 19 11 13 

In [17]:
#Python program to print all even numbers in a range
Lower=int(input("Enter lower limit "))
Upper=int(input("Enter upper limit "))

print("Even numbers in the range are")

# loop

for i in range(Lower,Upper):
    if i%2==0:
        print(i,end=" ")

Enter lower limit 10
Enter upper limit 50
Even numbers in the range are
10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 

In [18]:
#Python program to print all odd numbers in a range
Lower=int(input("Enter lower limit "))
Upper=int(input("Enter upper limit "))

print("Even numbers in the range are")

# loop

for i in range(Lower,Upper):
    if i%2!=0:
        print(i,end=" ")

Enter lower limit 10
Enter upper limit 50
Even numbers in the range are
11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 

In [19]:
#Python program to print positive numbers in a list
My_list = [-10,3,-9,-11,20,13]
# iterating each number in list
for num in My_list:
 
    # checking condition
    if num >= 0:
        print(num, end=" ")

3 20 13 

In [20]:
#Python program to print negative numbers in a list
My_list = [-10,3,-9,-11,20,13]
# iterating each number in list
for num in My_list:
 
    # checking condition
    if num < 0:
        print(num, end=" ")

-10 -9 -11 

In [21]:
#Python program to print all positive numbers in a range
start = int(input("Enter the start of range: ")) 
end = int(input("Enter the end of range: ")) 
  
# iterating each number in list 
for num in range(start, end + 1): 
  
    # checking condition 
    if num >= 0: 
        print(num, end=" ") 

Enter the start of range: 10
Enter the end of range: 20
10 11 12 13 14 15 16 17 18 19 20 

In [22]:
#Python program to print all negative numbers in a range
start = int(input("Enter the start of range: ")) 
end = int(input("Enter the end of range: ")) 
  
# iterating each number in list 
for num in range(start, end + 1): 
  
    # checking condition 
    if num < 0: 
        print(num, end=" ") 

Enter the start of range: -10
Enter the end of range: 10
-10 -9 -8 -7 -6 -5 -4 -3 -2 -1 

In [25]:
#Remove multiple element from an list
list1 = [11, 5, 17, 18, 23, 50] 

del list1[1:4]
 
print(list1)

[11, 23, 50]


In [26]:
#Remove empty from list
test_list = [5, 6, [], 3, [], [], 9]
 
# printing original list
print("The original list is : " + str(test_list))
 
# Remove empty List from List
while [] in test_list :
    test_list.remove([])
 
# printing result
print("List after empty list removal : " + str(test_list))

The original list is : [5, 6, [], 3, [], [], 9]
List after empty list removal : [5, 6, 3, 9]


In [27]:
#Python | Cloning or Copying a list
def Cloning(li1): 
    li_copy = li1
    return li_copy 
    
li1 = [4, 8, 2, 10, 15, 18] 
li2 = Cloning(li1) 
print("Original List:", li1) 
print("After Cloning:", li2)

Original List: [4, 8, 2, 10, 15, 18]
After Cloning: [4, 8, 2, 10, 15, 18]


In [28]:
# occurence in element
def countX(lst, x):
    return lst.count(x)

lst = [8, 6, 8, 10, 8, 20, 10, 8, 8]
x = 8
print('{} has occurred {} times'.format(x, countX(lst, x)))

8 has occurred 5 times


In [29]:
#Remove empty turple from a list
def Remove(tuples):
    while () in tuples:
        tuples.remove(());
    return tuples
 
# Driver Code
tuples = [(), ('ram','15','8'), (), ('laxman', 'sita'),
        ('krishna', 'Mahadev', '45'), ('',''),()]
print (Remove(tuples))

[('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'Mahadev', '45'), ('', '')]


In [30]:
#Duplicate value in list

lis = [1, 2, 1, 2, 3, 4, 5, 1, 1, 2, 5, 6, 7, 8, 9, 9]
x = []
y = []
for i in lis:
    if i not in x:
        x.append(i)
for i in x:
    if lis.count(i) > 1:
        y.append(i)
print(y)


[1, 2, 5, 9]


In [31]:
#Python program to find Cumulative sum of a list
list=[10,20,30,40,50]
new_list=[] 
j=0
for i in range(0,len(list)):
    j+=list[i]
    new_list.append(j) 
     
print(new_list) 

[10, 30, 60, 100, 150]


In [35]:
#Python | Sum of number ddef getSum(n):
def getSum(n):
    sum = 0
    while (n != 0):
        sum = sum + (n % 10)
        n = n//10
    return sum
   
n = 235
print(getSum(n))


10


In [36]:
#Break a list into chunks of size N in Python using Numpy

import numpy as np 
  
arr = range(30) 
np.array_split(arr, 6)


[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24]),
 array([25, 26, 27, 28, 29])]

In [1]:
#Python | Sort the values of first list using second list

import numpy as np
 
def sort_list(list1, list2):
    # Use numpy's argsort function to get the indices that would sort the second list
    idx = np.argsort(list2)
    # Index the first list using the sorted indices and return the result as a numpy array
    return np.array(list1)[idx]
 
# Define two lists of strings and integers to be used as inputs for the sort_list function
x = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]
y = [0, 1, 1, 0, 1, 2, 2, 0, 1]
 
# Call the sort_list function with the two lists and print the result
print(sort_list(x, y))
 
# Define another two lists of strings and integers to be used as inputs for the sort_list function
x = ["g", "e", "e", "k", "s", "f", "o", "r", "g", "e", "e", "k", "s"]
y = [0, 1, 1, 0, 1, 2, 2, 0, 1]
 
# Call the sort_list function with the two lists and print the result
print(sort_list(x, y))


['a' 'd' 'h' 'b' 'c' 'e' 'i' 'f' 'g']
['g' 'k' 'r' 'e' 'e' 's' 'g' 'f' 'o']


In [ ]:
Python Program for Matrix

In [2]:
#Python program to add two Matrices
import numpy as np
  
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = np.array(X) + np.array(Y)
 
print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [3]:
#Python program to multiply two matrices
import numpy as np
# take a 3x3 matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix
B = [[5, 8, 1, 2],
    [6, 6, 3, 4],
    [4, 5, 9, 1]]
 
# result will be 3x4
 
result= [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]
 
result = np.dot(A,B)
 
for r in result:
    print(r)

[114 153  60  55]
[74 92 73 34]
[119 149 112  55]


In [4]:
#Python program for matrix of product
import numpy as np

A = [[12, 7, 3], [4, 5, 6], [7, 8, 9]]
B = [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]

result= [[0,0,0,0], [0,0,0,0], [0,0,0,0]]
result= np.dot(A,B)

for p in result:
    print(p)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


In [5]:
#Adding and Subtracting Matrices in Python
import numpy as np
 
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
 
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
 
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

# Substracting
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [6]:
#Transpose a matrix in Single line in Python
import numpy
matrix = [[1, 2, 3], [4, 5, 6]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))


[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


In [7]:
#Python | Matrix creation of n*n
n = 4
matrix = [list(range(1 + n * i, 1 + n * (i + 1))) for i in range(n)]
print("The created matrix of {} * {}: ".format(n,n))
for m in matrix:
    print(m)

The created matrix of 4 * 4: 
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


In [8]:
#Python | Get Kth Column of Matrix
import numpy as np
# initialize list
test_list = [[4, 5, 6], [8, 11, 10], [7, 12, 15]]
# printing original list
print("The original list is : " + str(test_list))
#initialize K
K = 2
# Get Kth Column of Matrix
# using numpy
res = np.array(test_list)[:,K]
# printing result
print("The Kth column of matrix is : " + str(res))

The original list is : [[4, 5, 6], [8, 11, 10], [7, 12, 15]]
The Kth column of matrix is : [ 6 10 15]


In [9]:
#Python – Vertical Concatenation in Matrix

import numpy as np 
# initializing list
test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]
 
# find the maximum length of a sublist
max_len = max(len(sublist) for sublist in test_list)
 
# pad the sublists with empty strings to make them the same length
padded_list = [sublist + [''] * (max_len - len(sublist)) for sublist in test_list]
 
# convert the list to a numpy array
arr = np.array(padded_list)
 
# use transpose to switch rows and columns
arr_t = arr.T
 
# use join to concatenate the strings in each row
res = [''.join(row) for row in arr_t]
 
# print the result
print("List after column concatenation: " + str(res))


List after column concatenation: ['GfgisBest', 'goodfor']


In [ ]:
Python program for string 

In [10]:
#Python program to check if a string is palindrome or not
def isPalindrome(s):
    return s == s[::-1]

s = "malayalam"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")

Yes


In [13]:
#Python program to check whether the string is Symmetrical or Palindrome

string = 'abaabaaba'
half = int(len(string) / 2)
 
 
first_str = string[:half]
second_str = string[half:]
 
 
# symmetric
if first_str == second_str:
    print(string, 'string is symmetrical')
else:
    print(string, 'string is not symmetrical')
 
# palindrome
if first_str == second_str[::-1]:  # ''.join(reversed(second_str)) [slower]
    print(string, 'string is palindrome')
else:
    print(string, 'string is not palindrome')


abaabaaba string is not symmetrical
abaabaaba string is not palindrome


In [14]:
#Reverse words in a given String in Python
# input string
string = "i like this program very much"

# spliting words in the given string
# using slicing reverse the words
s = string.split()[::-1]

# joining the reversed string and
# printing the output
print(" ".join(s))


much very program this like i


In [17]:
#Ways to remove i’th character from string in Python

str = 'MilonjyotiBorah'
  
print(str.translate({ord(i): None for i in 'jyoti'}))


MlnBrah


In [18]:
#Python | Check if a Substring is Present in a Given String
MyString1 = "My Name is Milonjyoti Borah"
 
if "is" in MyString1:
    print("Yes! it is present in the string")
else:
    print("No! it is not present")

Yes! it is present in the string


In [21]:
#Python – Words Frequency in String Shorthands
string=" I name is Milon, and Her name is Jannavi "
print(string) 

# dictionary and count() and split()
word= {key: string.count(key) for key in string.split()}

# print result
print("Words in the string")
print(word)

 I name is Milon, and Her name is Jannavi 
Words in the string
{'I': 1, 'name': 2, 'is': 2, 'Milon,': 1, 'and': 1, 'Her': 1, 'Jannavi': 1}


In [22]:
#Python – Convert Snake case to Pascal case
from string import capwords

string= "program_tutorial"
print("Snake case: ",string)

pascal= capwords(string.replace('_',' '))
pascal= pascal.replace(' ','')

print("Pascal case: ",pascal)

Snake case:  program_tutorial
Pascal case:  ProgramTutorial


In [26]:
#Find length of a string in python (4 ways)
#1st
str = "Milon"
print(len(str))

#2nd
def findLen(str):
    counter = 0   
    for i in str:
        counter += 1
    return counter
 
 
str = "Milonjyoti"
print(findLen(str))

#3rd
def find_Len(string):
    return sum( 1 for i in string);

string = 'Hi Guyz'
print(find_Len(string))

#4th
string = "Python language"
s = 0
for i, a in enumerate(string):
    s += 1
print(s)


5
10
7
15


In [27]:
#Python program to print even length words in a string
n="This is a python language"
#splitting the words in a given string
s=n.split(" ") 
for i in s: 
  #checking the length of words
  if len(i)%2==0: 
    print(i)

This
is
python
language


In [28]:
#Python program to accept the strings which contains all vowels


IndentationError: expected an indented block (<ipython-input-28-e5ca8465beea>, line 8)

In [29]:

def check(string):
    string = string.replace(' ', '')
    string = string.lower()
    vowel = [string.count('a'), string.count('e'), string.count(
        'i'), string.count('o'), string.count('u')]
 
    # If 0 is present int vowel count array
    if vowel.count(0) > 0:
        return('not accepted')
    else:
        return('accepted')
 
 
# Driver code
if __name__ == "__main__":
 
    string = "SEEquoiaL"
 
    print(check(string))


accepted


In [30]:
#Python | Count the Number of matching characters in a pair of string
def count(s1, s2):
    c=0 #counter variable
    j=0
    for i in s1:
        if s2.find(i)>-0 and j==s1.find(i):
            c=c+1
        j=j+1
    print("Matching char: ",c)

s1="aabcdefk12"
s2="b2acdefk1"
count(s1,s2)

Matching char:  8


In [31]:
#Remove all duplicates from a given string in Python
string = "malayalam"
p = ""
for char in string:
    if char not in p:
        p = p+char
print(p)
k = list("malayalam")


maly


In [33]:
#Python – Least Frequent Character in String
import numpy as np
def least_frequent_char(string):
    freq = {char: string.count(char) for char in set(string)}
    return list(freq.keys())[np.argmin(list(freq.values()))]
# Example usage
input_string = "malayalam"
min_char = least_frequent_char(input_string)
print("The original string is:", input_string)
print("The minimum of all characters in", input_string, "is:", min_char)

The original string is: malayalam
The minimum of all characters in malayalam is: y


In [35]:
#Python | Maximum frequency character in String

test_str = "malayalam"
res = max(test_str, key=lambda x: test_str.count(x))
print(res)


a


In [36]:
#Python | Program to check if a string contains any special character
import string
 
def check_string(s):
    for c in s:
        if c in string.punctuation:
            print("String is not accepted")
            return
    print("String is accepted")
 
# Example usage
check_string("ma@#mals@las")  # Output: String is not accepted
check_string("Hello I am Milon")  # Output: String is accepted


String is not accepted
String is accepted


In [38]:
#Generating random strings until a given string is generated
import string
import random
import time
  
# all possible characters including lowercase, uppercase and punctuations
possibleChar = string.ascii_lowercase + string.digits + string.ascii_uppercase + ' ., !?;:'
  
# string to be generated
t = "Milon"
  
attemptThis = ''.join(random.choice(possibleChar) for i in range(len(t)))
attemptNext = ''
  
done= False
iteration = 0
  
# Iterate while done is false
while done == False:
    print(attemptThis)
      
    attemptNext = ''
    done = True
      
    # if matches with string 
    # change index
    for i in range(len(t)):
        if attemptThis[i] != t[i]:
            done = False
            attemptNext += random.choice(possibleChar)
        else:
            attemptNext += t[i]
              
    # increase iteration
    iteration = iteration + 1
    attemptThis = attemptNext
    time.sleep(0.1)

print("Target matched after ",iteration," iterations")

vI:QG
zPeLf
SlhFn
 6w0n
afaLn
.8bRn
Bkhcn
lRqin
N;hIn
jsNpn
,UnAn
NFqon
6 qon
OLWon
Y3con
M.ion
MR on
MaLon
M0ron
M8Kon
MHeon
MU0on
M4eon
Mr on
MDzon
MkGon
MG;on
MQDon
MEKon
Mejon
Mfson
MQWon
MGAon
Mhnon
M4Con
My9on
Mpwon
MB;on
MxCon
MISon
Mbuon
M7hon
MKIon
Mdton
MQoon
M;lon
MSlon
M6lon
MIlon
M9lon
Melon
MPlon
M0lon
Malon
MClon
MIlon
MKlon
M8lon
MFlon
Mblon
M1lon
MRlon
M2lon
Mylon
MRlon
M3lon
Molon
M lon
MVlon
Mrlon
Mdlon
MFlon
Mplon
MDlon
MBlon
MHlon
MXlon
MRlon
Mwlon
MJlon
M8lon
Mslon
MJlon
MJlon
M,lon
M5lon
Mwlon
Malon
Mvlon
M:lon
MQlon
Mulon
MSlon
M?lon
MLlon
MNlon
Mblon
MDlon
M.lon
M8lon
M!lon
M8lon
MZlon
MClon
M6lon
MUlon
M2lon
Mylon
Mdlon
M;lon
Mmlon
M2lon
M.lon
MWlon
Melon
Mvlon
Malon
M,lon
MHlon
M?lon
Mrlon
Mnlon
M6lon
Mvlon
M;lon
Mflon
MClon
Mmlon
MTlon
Mylon
M,lon
Molon
Mglon
MVlon
Molon
MFlon
Melon
M1lon
MFlon
MMlon
Malon
MWlon
M:lon
M9lon
Mxlon
Mvlon
MWlon
M7lon
MElon
Mjlon
MIlon
MOlon
Mjlon
M?lon
Mvlon
Mplon
MXlon
MPlon
MHlon
MQlon
M;lon
M5lon
M8lon
Mmlon
MYlon
Mflon
MFlo

In [40]:
#Find words which are greater than given length k

sentence = "Hi guyz, My name is Abhishek"
length = 6
print([word for word in sentence.split() if len(word) > length])


['Abhishek']


In [41]:
#Python program for removing i-th character from a string
def remove(string, i): 
  
    a = string[: i] 
  
    # Characters after the nth indexed 
    # is stored in a variable b 
    b = string[i + 1:] 
  
    # Returning string after removing 
    # nth indexed character. 
    return a + b 
if __name__ == '__main__': 
  
    string = "Miloonjyoti"
  
    # Remove nth index element 
    i = 5
  
    # Print the new string 
    print(remove(string, i)) 

Miloojyoti


In [43]:
#Python program to split and join a string
s = 'This is a python code'
# print the string after split method
print(s.split(" ")) 
# print the string after join method
print("_".join(s.split()))
 

['This', 'is', 'a', 'python', 'code']
This_is_a_python_code


In [2]:
#Python | Check if a given string is binary string or not
def check(string) :
    b = set(string)
    s = {'0', '1'}
    if s == b or b == {'0'} or b == {'1'}:
        print("Binary String")
    else :
        print("Non Binary String")
  
s1= "00110101"
# function calling
check(s1)
s2 = "1010100abc00111"
check(s2)

Binary String
Non Binary String


In [3]:
#Python program to find uncommon words from two Strings
def UncommonWords(A, B):
    A=A.split()
    B=B.split()
    x=[]
    for i in A:
        if i not in B:
            x.append(i)
    for i in B:
        if i not in A:
            x.append(i)
    x=list(set(x))
    return x

A = "Hi I am Milon"
B = "And I am from Jorhat"
 
# Print required answer
print(UncommonWords(A, B))

['And', 'Jorhat', 'Hi', 'Milon', 'from']


In [4]:
#Python – Replace duplicate Occurrence in String
test_string = 'James is good in Science , Science is James favourite subject. '
  
# printing original string
print("The original string is : " + str(test_string))
  
# initializing replace mapping 
repl_dict = {'James' :  'his', 'Science' : 'it' }
  
# Replace duplicate Occurrence in String
# Using keys() + index() + list comprehension
test_list = test_string.split(' ')
res = ' '.join([repl_dict.get(val) if val in repl_dict.keys() and test_list.index(val) != index 
                                   else val for index, val in enumerate(test_list)])
print("The string after replacing : " + str(res))

The original string is : James is good in Science , Science is James favourite subject. 
The string after replacing : James is good in Science , it is his favourite subject. 


In [5]:
#Python – Replace multiple words with K
test_string = 'Studytonight has best tutorials in python'
print("The original string is : " + str(test_string))
  
word_list = ["best", 'tutorials', 'python']
replace_word = 'k'
replaced_string = ' '.join([replace_word if i in word_list else i for i in test_string.split()])
  
print("String after multiple replace : " + str(replaced_string)) 

The original string is : Studytonight has best tutorials in python
String after multiple replace : Studytonight has k k in k


In [6]:
#Python | Permutation of a given string using inbuilt function
from itertools import permutations
 
# Initialising string
ini_str = "abc"
 
# Printing initial string
print("Initial string", ini_str)
 
# Finding all permutation
permutation = [''.join(p) for p in permutations(ini_str)]
# Printing result
print("Resultant List", str(permutation))

Initial string abc
Resultant List ['abc', 'acb', 'bac', 'bca', 'cab', 'cba']


In [9]:
#Python | Check for URL in a String
def Find(string):
    x=string.split()
    res=[]
    for i in x:
        if i.find("https:")==0 or i.find("http:")==0:
            res.append(i)
    return res
             
# Driver Code
string = 'Google: https://google.com'
print("Yes,we found Urls in this string: ", Find(string))

Yes,we found Urls in this string:  ['https://google.com']


In [11]:
#Execute a String of Code in Python
str1 = "30 + 51"

print("The output of the code present in the string is ")
print(eval(str1))

The output of the code present in the string is 
81


In [12]:
#
def rotate(input,d):
 
    # slice string in two parts for left and right
    Lfirst = input[0 : d]
    Lsecond = input[d :]
    Rfirst = input[0 : len(input)-d]
    Rsecond = input[len(input)-d : ]
 
    # now concatenate two parts together
    print ("Left Rotation : ", (Lsecond + Lfirst) )
    print ("Right Rotation : ", (Rsecond + Rfirst))
if __name__ == "__main__":
    input = 'MilonjyotiBorah'
    d=2
    rotate(input,d)

Left Rotation :  lonjyotiBorahMi
Right Rotation :  ahMilonjyotiBor


In [30]:
#String slicing in Python to check if a string can become empty by recursive deletion
def canBecomeEmpty(string, sub_str):
    while len(string) > 0:
 
        # idx: to store starting index of sub-
        #     string found in the original string
        idx = string.find(sub_str)
 
        if idx == -1:
            break
 
        # Erasing the found sub-string from
        # the original string
        string = string.replace(sub_str, "", 1)
 
    return (len(string) == 0)
 
# Driver code
if __name__ == "__main__":
    string = "Milonjyoti"
    sub_str = "Borah"
    if canBecomeEmpty(string, sub_str):
        print("Yes")
    else:
        print("No")

No


In [14]:
#Python Counter| Find all duplicate characters in string
def find_duplicates(string):
    # Initialize an empty list to store duplicate letters
    duplicates = []
    
    # Loop over each letter in the string
    for letter in string:
        # Check if the letter appears more than once and if it's not already in the duplicates list
        if string.count(letter) > 1 and letter not in duplicates:
            # Append the letter to the duplicates list
            duplicates.append(letter)
    
    # Return the list of duplicate letters
    return duplicates

#test
string = "thannk youu"
duplicates = find_duplicates(string)
print(duplicates)

['n', 'u']


In [16]:
#Python – Replace all occurrences of a substring in a string
input_string = "Hi I am Milon"
s1 = "Milon"
s2 = "MBorah"
input_string = input_string.replace(s1, s2)
print(input_string)

Hi I am MBorah


In [ ]:
Dictionary Program in Python

In [17]:
#Python – Extract Unique values dictionary values
test_dict = {'gfg': [5, 6, 7, 8],
             'is': [10, 11, 7, 5],
             'best': [6, 12, 10, 8],
             'for': [1, 2, 5]}
 
# printing original dictionary
print("The original dictionary is : " + str(test_dict))
 
# Extract Unique values dictionary values
# Using set comprehension + values() + sorted()
res = list(sorted({abc for val in test_dict.values() for abc in val}))
 
# printing result
print("The unique values list is : " + str(res))

The original dictionary is : {'gfg': [5, 6, 7, 8], 'is': [10, 11, 7, 5], 'best': [6, 12, 10, 8], 'for': [1, 2, 5]}
The unique values list is : [1, 2, 5, 6, 7, 8, 10, 11, 12]


In [19]:
#Python program to find the sum of all items in a dictionary
def returnSum(myDict):
 
    list = []
    for i in myDict:
        list.append(myDict[i])
    final = sum(list)
 
    return final
dict = {'a': 156, 'b': 500, 'c': 350}
print("Sum :", returnSum(dict))

Sum : 1006


In [21]:
#Python | Ways to remove a key from dictionary
test_dict = {"Arushi": 25, "Manika": 22, "Rajib": 23}
 
# Printing dictionary before removal
print("The dictionary before performing remove is : ", test_dict)
 
# Using del to remove a dict
# removes Mani
del test_dict['Arushi']
 
# Printing dictionary after removal
print("The dictionary after remove is : ", test_dict)

The dictionary before performing remove is :  {'Arushi': 25, 'Manika': 22, 'Rajib': 23}
The dictionary after remove is :  {'Manika': 22, 'Rajib': 23}


In [22]:
#Ways to sort list of dictionaries by values in Python – Using itemgetter
from operator import itemgetter

my_list = [{ "name" : "Will", "age" : 56},
          { "name" : "Rob", "age" : 20 },
          { "name" : "Mark" , "age" : 34 },
          { "name" : "John" , "age" : 24 }]

print("The list sorted by age is : ")
print(sorted(my_list, key=itemgetter('age')))

print("The list sorted by age and name is : ")
print(sorted(my_list, key=itemgetter('age', 'name')))

print("The list sorted by age in descending order is : ")
print(sorted(my_list, key=itemgetter('age'),reverse = True))

The list sorted by age is : 
[{'name': 'Rob', 'age': 20}, {'name': 'John', 'age': 24}, {'name': 'Mark', 'age': 34}, {'name': 'Will', 'age': 56}]
The list sorted by age and name is : 
[{'name': 'Rob', 'age': 20}, {'name': 'John', 'age': 24}, {'name': 'Mark', 'age': 34}, {'name': 'Will', 'age': 56}]
The list sorted by age in descending order is : 
[{'name': 'Will', 'age': 56}, {'name': 'Mark', 'age': 34}, {'name': 'John', 'age': 24}, {'name': 'Rob', 'age': 20}]


In [24]:
#Ways to sort list of dictionaries by values in Python – Using lambda function
list = [{"name": "Nandi", "age": 20},
       {"name": "Manjeet", "age": 23},
       {"name": "Nikhil", "age": 19}]
 
# using sorted and lambda to print list sorted
# by age
print("The list printed sorting by age: ")
print(sorted(list, key=lambda i: i['age']))
 
print("\r")
 
# using sorted and lambda to print list sorted
# by both age and name. Notice that "Manjeet"
# now comes before "Nandini"
print("The list printed sorting by age and name: ")
print(sorted(list, key=lambda i: (i['age'], i['name'])))
 
print("\r")
 
# using sorted and lambda to print list sorted
# by age in descending order
print("The list printed sorting by age in descending order: ")
print(sorted(list, key=lambda i: i['age'], reverse=True))

The list printed sorting by age: 
[{'name': 'Nikhil', 'age': 19}, {'name': 'Nandi', 'age': 20}, {'name': 'Manjeet', 'age': 23}]

The list printed sorting by age and name: 
[{'name': 'Nikhil', 'age': 19}, {'name': 'Nandi', 'age': 20}, {'name': 'Manjeet', 'age': 23}]

The list printed sorting by age in descending order: 
[{'name': 'Manjeet', 'age': 23}, {'name': 'Nandi', 'age': 20}, {'name': 'Nikhil', 'age': 19}]


In [25]:
#Python | Merging two Dictionaries
def Merge(dict1, dict2):
    return(dict2.update(dict1))
dict1 = {'a': 10, 'b': 8}
dict2 = {'d': 6, 'c': 4}
 
# This returns None
print(Merge(dict1, dict2))
 
# changes made in dict2
print(dict2)

None
{'d': 6, 'c': 4, 'a': 10, 'b': 8}


In [27]:
#Python – Convert key-values list to flat dictionary

test_dict = {'month': [1, 2, 3], 'name': ['Jan', 'Feb', 'March']}
res = {test_dict['month'][i]: test_dict['name'][i] for i in range(len(test_dict['month']))}
print("Flattened dictionary:", res)


Flattened dictionary: {1: 'Jan', 2: 'Feb', 3: 'March'}


In [28]:
#Python – Insertion at the beginning in OrderedDict
from collections import OrderedDict
 
# Initialising ordered_dict
iniordered_dict = OrderedDict([('akhil', '2'), ('nikhil', '5')])
 
# Inserting items in starting of dict
iniordered_dict.update({'manjeet': '3'})
iniordered_dict.move_to_end('manjeet', last=False)
 
# Printing result
print("Resultant Dictionary : "+str(iniordered_dict))

Resultant Dictionary : OrderedDict([('manjeet', '3'), ('akhil', '2'), ('nikhil', '5')])


In [29]:
#Python | Check order of character in string using OrderedDict( )
from collections import OrderedDict 
 
def checkOrder(input, pattern): 
     
    # create empty OrderedDict 
    # output will be like {'a': None,'b': None, 'c': None} 
    dict = OrderedDict.fromkeys(input) 
 
    # traverse generated OrderedDict parallel with 
    # pattern string to check if order of characters 
    # are same or not 
    ptrlen = 0
    for key,value in dict.items(): 
        if (key == pattern[ptrlen]): 
            ptrlen = ptrlen + 1
         
        # check if we have traverse complete 
        # pattern string 
        if (ptrlen == (len(pattern))): 
            return 'true'
 
    # if we come out from for loop that means 
    # order was mismatched 
    return 'false'
 
# Driver program 
if __name__ == "__main__": 
    input = 'engineers rock'
    pattern = 'er'
    print (checkOrder(input,pattern)) 

true


In [31]:
#Dictionary and counter in Python to find winner of election

from collections import Counter 
 
votes =['john','johnny','jackie','johnny','john','jackie',
    'jamie','jamie','john','johnny','jamie','johnny','john'] 
 
#Count the votes for persons and stores in the dictionary
vote_count=Counter(votes)
 
#Find the maximum number of votes
max_votes=max(vote_count.values())
 
#Search for people having maximum votes and store in a list
lst=[i for i in vote_count.keys() if vote_count[i]==max_votes]
 
#Sort the list and print lexicographical smallest name
print(sorted(lst)[0])


john


In [34]:
#Python – Append Dictionary Keys and Values ( In order ) in dictionary
test_dict = {"Gfg": 1, "is": 3, "Best": 2}
 
# printing original dictionary
print("The original dictionary is : " + str(test_dict))
 
# using the zip() function and list comprehension to append dictionary keys and values
res = [val for val in zip(test_dict.values(), test_dict.keys())]
 
# printing result
print("The ordered keys and values : " + str(res))

The original dictionary is : {'Gfg': 1, 'is': 3, 'Best': 2}
The ordered keys and values : [(1, 'Gfg'), (3, 'is'), (2, 'Best')]


In [37]:
#Python | Sort Python Dictionaries by Key or Value
def dictionary():
    # Declare hash function
    key_value = {}
 
# Initializing value
    key_value[2] = 45
    key_value[1] = 18
    key_value[5] = 10
    key_value[4] = 333
    key_value[6] = 17
    key_value[3] = 99 
    print("Task 1:-\n")
 
    print("key_value", key_value)
 
    # iterkeys() returns an iterator over the
    # dictionary’s keys.
    for i in sorted(key_value.keys()):
        print(i, end=" ")
 
 
def main():
    # function calling
    dictionary()
 
 
# Main function calling
if __name__ == "__main__":
    main()


Task 1:-

key_value {2: 45, 1: 18, 5: 10, 4: 333, 6: 17, 3: 99}
1 2 3 4 5 6 

In [39]:
#Python – Sort Dictionary key and values List
test_dict = {'gfg': [7, 6, 3], 
             'is': [2, 10, 3], 
             'best': [19, 4]}
 
# printing original dictionary
print("The original dictionary is : " + str(test_dict))
 
# Sort Dictionary key and values List
# Using dictionary comprehension + sorted()
res = {key : sorted(test_dict[key]) for key in sorted(test_dict)}
 
# printing result 
print("The sorted dictionary : " + str(res)) 

The original dictionary is : {'gfg': [7, 6, 3], 'is': [2, 10, 3], 'best': [19, 4]}
The sorted dictionary : {'best': [4, 19], 'gfg': [3, 6, 7], 'is': [2, 3, 10]}


In [40]:
#Handling missing keys in Python dictionaries

a = {'a': 5, 'c': 8, 'e': 2}
if "q" in a:
    print(a["d"])
else:
    print("Key not found")


Key not found


In [41]:
#Python dictionary with keys having multiple inputs
import random as rn
 
# creating an empty dictionary
dict = {}
 
# Insert first triplet in dictionary
x, y, z = 10, 20, 30
dict[x, y, z] = x + y - z;
 
# Insert second triplet in dictionary
x, y, z = 5, 2, 4
dict[x, y, z] = x + y - z;
 
# print the dictionary
print(dict)

{(10, 20, 30): 0, (5, 2, 4): 3}


In [43]:
#Print anagrams together in Python using List and Dictionary
def Anagram(d1): 
      
    # empty dictionary for anagrams together 
    dict = {} 
  
    # traversal 
    for val in d1: 
          
        # sorts list
        key = ''.join(sorted(val)) 
          
        if key in dict.keys(): 
            dict[key].append(val) 
        else: 
            dict[key] = [] 
            dict[key].append(val) 
  
    # traverse dictionary and join keys together 
    result = "" 
    for key,value in dict.items(): 
        result = result + ' '.join(value) + ' '
  
    return result 
  
d1=['act', 'cat', 'silent','listen']
print("Words: ",d1)
print("Anagram: ",Anagram(d1))

Words:  ['act', 'cat', 'silent', 'listen']
Anagram:  act cat silent listen 


In [44]:
#K’th Non-repeating Character in Python using List Comprehension and OrderedDict
from collections import OrderedDict
 
def kthRepeating(input,k):
 
    # OrderedDict returns a dictionary data
        # structure having characters of input
    # string as keys in the same order they
        # were inserted and 0 as their default value
    dict=OrderedDict.fromkeys(input,0)
 
    # now traverse input string to calculate
        # frequency of each character
    for ch in input:
        dict[ch]+=1
 
    # now extract list of all keys whose value
        # is 1 from dict Ordered Dictionary
    nonRepeatDict = [key for (key,value) in dict.items() if value==1]
     
    # now return (k-1)th character from above list
    if len(nonRepeatDict) < k:
        return 'Less than k non-repeating characters in input.'
    else:
        return nonRepeatDict[k-1]
 
# Driver function
if __name__ == "__main__":
    input = "Milonjyoti Borah"
    k = 3
    print (kthRepeating(input, k))

n


In [45]:
#Check if binary representations of two numbers are anagram
def is_anagram_binary(a, b):
    bin_a = bin(a)[2:].zfill(32)
    bin_b = bin(b)[2:].zfill(32)
    count_a = [0, 0]
    count_b = [0, 0]
    for i in range(32):
        if bin_a[i] == '0':
            count_a[0] += 1
        else:
            count_a[1] += 1
        if bin_b[i] == '0':
            count_b[0] += 1
        else:
            count_b[1] += 1
    if count_a == count_b:
        return "Yes"
    else:
        return "No"
 
a = 8
b = 9 
print( is_anagram_binary(8, 4))

Yes


In [46]:
#Python Counter to find the size of largest subset of anagram words

def largest_anagram_subset_size(words):
    anagram_dict = {}
    for word in words:
        sorted_word = ''.join(sorted(word))
        if sorted_word not in anagram_dict:
            anagram_dict[sorted_word] = []
        anagram_dict[sorted_word].append(word)
    max_count = max([len(val) for val in anagram_dict.values()])
    return max_count
 
words = ['ant', 'magenta', 'magnate', 'tan', 'gnamate']
print(largest_anagram_subset_size(words)) 


3


In [47]:
#Python | Remove all duplicates words from a given sentence

from collections import Counter
 
def remov_duplicates(input):
 
    # split input string separated by space
    input = input.split(" ")
 
    # now create dictionary using counter method
    # which will have strings as key and their 
    # frequencies as value
    UniqW = Counter(input)
 
    # joins two adjacent elements in iterable way
    s = " ".join(UniqW.keys())
    print (s)
if __name__ == "__main__":
    input = 'Python is great and Java is also great'
    remov_duplicates(input)


Python is great and Java also


In [54]:
#Counting the frequencies in a list using dictionary in Python

def CountFrequency(my_list):
 
    # Creating an empty dictionary
    freq = {}
    for item in my_list:
        if (item in freq):
            freq[item] += 1
        else:
            freq[item] = 1
 
    for key, value in freq.items():
        print("% d : % d" % (key, value))
 
 
# Driver function
if __name__ == "__main__":
    my_list = [1, 1, 1, 5, 5, 3, 1, 3, 3, 1, 4, 4, 4, 2, 2, 2, 2]
 
    CountFrequency(my_list)


 1 :  5
 5 :  2
 3 :  3
 4 :  3
 2 :  4


In [55]:
#Python | Convert a list of Tuples into Dictionary
def Convert(tup, di):
    for a, b in tup:
        di.setdefault(a, []).append(b)
    return di
tups = [("akash", 10), ("gaurav", 12), ("anand", 14),
        ("suraj", 20), ("akhil", 25), ("ashish", 30)]
dictionary = {}
print(Convert(tups, dictionary))

{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}


In [56]:
#Python counter and dictionary intersection example (Make a string using deletion and rearrangement)
from collections import Counter
 
def makeString(str1,str2):
 
    # convert both strings into dictionaries
    # output will be like str1="aabbcc",
    # dict1={'a':2,'b':2,'c':2}
    # str2 = 'abbbcc', dict2={'a':1,'b':3,'c':2}
    dict1 = Counter(str1)
    dict2 = Counter(str2)
 
    # take intersection of two dictionaries
    # output will be result = {'a':1,'b':2,'c':2}
    result = dict1 & dict2
 
    # compare resultant dictionary with first
    # dictionary comparison first compares keys
    # and then compares their corresponding values
    return result == dict1
 
# Driver program
if __name__ == "__main__":
    str1 = 'ABHISHEKsinGH'
    str2 = 'gfhfBHkooIHnfndSHEKsiAnG'
    if (makeString(str1,str2)==True):
        print("Possible")
    else:
        print("Not Possible")

Possible


In [58]:
#Python dictionary, set and counter to check if frequencies can become same

import operator
 
 
def CountFrequency(my_list):
 
    # Creating an empty dictionary
    freq = {}
    for items in my_list:
        freq[items] = my_list.count(items)
 
    for key, value in freq.items():
        print("% d : % d" % (key, value))
 
 
# Driver function
if __name__ == "__main__":
    my_list = [1, 1, 1, 5, 5, 3, 1, 3, 3, 1, 4, 4, 4, 2, 2, 2, 2]
    CountFrequency(my_list)


 1 :  5
 5 :  2
 3 :  3
 4 :  3
 2 :  4


In [62]:
#Scraping And Finding Ordered Words In A Dictionary using Python

import collections
 
# Creating a regular dictionary
print('Regular dictionary:')
d = {chr(k): k for k in range(ord('a'), ord('g'))}
 
for k, v in d.items():
    print(k, v)
 
# Creating an Ordered dictionary
print('\nOrderedDict:')
d = collections.OrderedDict()
[d.setdefault(chr(k), k) for k in range(ord('a'), ord('g'))]
 
for k, v in d.items():
    print(k, v)


Regular dictionary:
a 97
b 98
c 99
d 100
e 101
f 102

OrderedDict:
a 97
b 98
c 99
d 100
e 101
f 102


In [63]:
#Possible Words using given characters in Python
def charCount(word):
    dict = {}
    for i in word:
        dict[i] = dict.get(i, 0) + 1
    return dict
 
 
def possible_words(lwords, charSet):
    for word in lwords:
        flag = 1
        chars = charCount(word)
        for key in chars:
            if key not in charSet:
                flag = 0
            else:
                if charSet.count(key) != chars[key]:
                    flag = 0
        if flag == 1:
            print(word)
 
if __name__ == "__main__":
    input = ['goo', 'bat', 'me', 'eat', 'goal', 'boy', 'run']
    charSet = ['e', 'o', 'b', 'a', 'm', 'g', 'l']
    possible_words(input, charSet)

me
goal


In [65]:
#Python – Keys associated with Values in Dictionary
test_dict = {'gfg' : [1, 2, 3], 'is' : [1, 4], 'best' : [4, 2]} 
 
# printing original dictionary
print("The original dictionary is : " + str(test_dict))
 
# Values Associated Keys
# Using dict comprehension + loop
result_dict = {}
for key, val in test_dict.items():
    for ele in val:
        if ele in result_dict:
            result_dict[ele].append(key)
        else:
            result_dict[ele] = [key]
 
# printing result 
print("The values associated dictionary : " + str(result_dict))

The original dictionary is : {'gfg': [1, 2, 3], 'is': [1, 4], 'best': [4, 2]}
The values associated dictionary : {1: ['gfg', 'is'], 2: ['gfg', 'best'], 3: ['gfg'], 4: ['is', 'best']}


In [67]:
#Python program to Find the size of a Tuple

import sys
 
# sample Tuples
Tuple1 = ("A", 1, "B", 2, "C", 3)
Tuple2 = ("Milon", "Raju", "Abir", "Nikhil", "Rahul", "Deepanshu")
Tuple3 = ((1, "Lion"), ( 2, "Tiger"), (3, "Fox"), (4, "Wolf"))
 
# print the sizes of sample Tuples
print("Size of Tuple1: " + str(sys.getsizeof(Tuple1)) + "bytes")
print("Size of Tuple2: " + str(sys.getsizeof(Tuple2)) + "bytes")
print("Size of Tuple3: " + str(sys.getsizeof(Tuple3)) + "bytes")


Size of Tuple1: 88bytes
Size of Tuple2: 88bytes
Size of Tuple3: 72bytes


In [69]:
#Python – Maximum and Minimum K elements in Tuple
import heapq
test_tup = (5, 20, 3, 7, 6, 8)
# printing original tuple
print("The original tuple is : " + str(test_tup))
K = 2
smallest = heapq.nsmallest(K, test_tup)
largest = heapq.nlargest(K, test_tup)
result = tuple(sorted(smallest + largest))
print("The extracted values : " +str(result))

The original tuple is : (5, 20, 3, 7, 6, 8)
The extracted values : (3, 5, 8, 20)


In [70]:
#Create a list of tuples from given list having number and its cube in each tuple
list1 = [1, 2, 5, 6]
 
# using list comprehension to iterate each
# values in list and create a tuple as specified
res = [(val, pow(val, 3)) for val in list1]
 
# print the result
print(res)

[(1, 1), (2, 8), (5, 125), (6, 216)]


In [72]:
#Python – Adding Tuple to List and vice – versa
test_list = [5, 6, 7]
 
# printing original list
print("The original list is : " + str(test_list))
 
# initializing tuple 
test_tup = (9, 10)
 
# Adding Tuple to List and vice - versa
# Using += operator (list + tuple)
test_list += test_tup
 
# printing result 
print("The container after addition : " + str(test_list)) 

The original list is : [5, 6, 7]
The container after addition : [5, 6, 7, 9, 10]


In [73]:
#Python – Closest Pair to Kth index element in Tuple
test_list = [(3, 4), (78, 76), (2, 3), (9, 8), (19, 23)]
 
# printing original list
print("The original list is : " + str(test_list))
 
# initializing tuple
tup = (17, 23)
 
# initializing K 
K = 1
 
# Closest Pair to Kth index element in Tuple
# Using min() + lambda
res = min(range(len(test_list)), key = lambda sub: abs(test_list[sub][K - 1] - tup[K - 1]))
 
# printing result 
print("The nearest tuple to Kth index element is : " + str(test_list[res])) 

The original list is : [(3, 4), (78, 76), (2, 3), (9, 8), (19, 23)]
The nearest tuple to Kth index element is : (19, 23)


In [75]:
#Python – Join Tuples if similar initial element
test_list = [(5, 6), (5, 7), (6, 8), (6, 10), (7, 13)]
 
# printing original list
print("The original list is : " + str(test_list))
 
# Join Tuples if similar initial element
# Using loop
res = []
x = []
for i in test_list:
    if i[0] not in x:
        x.append(i[0])
for i in x:
    p = []
    p.append(i)
    for j in test_list:
        if i == j[0]:
            p.append(j[1])
    res.append(p)
 
# printing result
print("The extracted elements : " + str(res))

The original list is : [(5, 6), (5, 7), (6, 8), (6, 10), (7, 13)]
The extracted elements : [[5, 6, 7], [6, 8, 10], [7, 13]]


In [76]:
#Python – Extract digits from Tuple list
from itertools import chain
 
# initializing list
test_list = [(15, 3), (3, 9), (1, 10), (99, 2)]
 
# printing original list
print("The original list is : " + str(test_list))
 
# Extract digits from Tuple list
# Using map() + chain.from_iterable() + set() + loop
temp = map(lambda ele: str(ele), chain.from_iterable(test_list))
res = set()
for sub in temp:
    for ele in sub:
        res.add(ele)
 
# printing result 
print("The extracted digits : " + str(res)) 

The original list is : [(15, 3), (3, 9), (1, 10), (99, 2)]
The extracted digits : {'1', '9', '5', '3', '2', '0'}


In [77]:
#Python – All pair combinations of 2 tuples
test_tuple1 = (4, 5)
test_tuple2 = (7, 8)
 
# printing original tuples
print("The original tuple 1 : " + str(test_tuple1))
print("The original tuple 2 : " + str(test_tuple2))
 
# All pair combinations of 2 tuples
# Using list comprehension
res =  [(a, b) for a in test_tuple1 for b in test_tuple2]
res = res +  [(a, b) for a in test_tuple2 for b in test_tuple1]
 
# printing result 
print("The filtered tuple : " + str(res))

The original tuple 1 : (4, 5)
The original tuple 2 : (7, 8)
The filtered tuple : [(4, 7), (4, 8), (5, 7), (5, 8), (7, 4), (7, 5), (8, 4), (8, 5)]


In [78]:
#Python – Remove Tuples of Length K
test_list = [(4, 5), (4, ), (8, 6, 7), (1, ), (3, 4, 6, 7)]
 
# printing original list
print("The original list : " + str(test_list))
 
# initializing K 
K = 1
 
# 1 liner to perform task
# filter just lengths other than K 
# len() used to compute length
res = [ele for ele in test_list if len(ele) != K]
 
# printing result 
print("Filtered list : " + str(res))

The original list : [(4, 5), (4,), (8, 6, 7), (1,), (3, 4, 6, 7)]
Filtered list : [(4, 5), (8, 6, 7), (3, 4, 6, 7)]


In [79]:
#Sort a list of tuples by second Item
def Sort_Tuple(tup):
 
    # getting length of list of tuples
    lst = len(tup)
    for i in range(0, lst):
 
        for j in range(0, lst-i-1):
            if (tup[j][1] > tup[j + 1][1]):
                temp = tup[j]
                tup[j] = tup[j + 1]
                tup[j + 1] = temp
    return tup
 
 
# Driver Code
tup = [('for', 24), ('is', 10), ('Geeks', 28),
       ('MilonjyotiBorah', 5), ('portal', 20), ('a', 15)]
 
print(Sort_Tuple(tup))

[('MilonjyotiBorah', 5), ('is', 10), ('a', 15), ('portal', 20), ('for', 24), ('Geeks', 28)]


In [80]:
#Python program to Order Tuples using external List
test_list = [('Gfg', 3), ('best', 9), ('CS', 10), ('Geeks', 2)]
 
# printing original list
print("The original list is : " + str(test_list))
 
# initializing order list
ord_list = ['Geeks', 'best', 'CS', 'Gfg']
 
res=[]
x=[]
for i in test_list:
    x.append(i[0])
for i in ord_list:
    if i in x:
        res.append(test_list[x.index(i)])
# printing result
print("The ordered tuple list : " + str(res))

The original list is : [('Gfg', 3), ('best', 9), ('CS', 10), ('Geeks', 2)]
The ordered tuple list : [('Geeks', 2), ('best', 9), ('CS', 10), ('Gfg', 3)]


In [81]:
#Python – Flatten tuple of List to tuple
test_tuple = ([5, 6], [6, 7, 8, 9], [3])
 
# printing original tuple
print("The original tuple : " + str(test_tuple))
 
# Flatten tuple of List to tuple
# Using sum() + tuple()
res = tuple(sum(test_tuple, []))
 
# printing result
print("The flattened tuple : " + str(res))

The original tuple : ([5, 6], [6, 7, 8, 9], [3])
The flattened tuple : (5, 6, 6, 7, 8, 9, 3)


In [82]:
#Python – Convert Nested Tuple to Custom Key Dictionary
test_tuple = ((4, 'Gfg', 10), (3, 'is', 8), (6, 'Best', 10)) 
 
# printing original tuple 
print("The original tuple : " + str(test_tuple)) 
 
# Convert Nested Tuple to Custom Key Dictionary 
# Using list comprehension + dictionary comprehension 
res = [{'key': sub[0], 'value': sub[1], 'id': sub[2]} 
                            for sub in test_tuple] 
 
# printing result 
print("The converted dictionary : " + str(res)) 

The original tuple : ((4, 'Gfg', 10), (3, 'is', 8), (6, 'Best', 10))
The converted dictionary : [{'key': 4, 'value': 'Gfg', 'id': 10}, {'key': 3, 'value': 'is', 'id': 8}, {'key': 6, 'value': 'Best', 'id': 10}]
